### ISSUE TITLE
Linker cant detect language

### ISSUE THREAD

**Issue by c0ntradicti0n** [mauvilsa/tesseract-recognize#3]
I ran into this error after installing the required libraries ob ubuntu 18.04.02. I googled around and tried in 'CMakeLists.txt' to set the language, but I have no idea, what I'm doing there and it didn't work. Can you help me?

`CMake Error at CMakeLists.txt:15 (add_executable):
  Cannot find source file:

    /home/xxxxxxx/Code/pic2tab/tesseract-recognize/PageXML.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: tesseract-recognize
CMake Error: Cannot determine link language for target "tesseract-recognize".
-- Generating done
-- Build files have been written to: /home/xxxxxxxxxx/Code/pic2tab/tesseract-recognize
`

**Comment by c0ntradicti0n** [comment]
Ah, the problem orgininated, that the pageXML-folder is not automatically cloned whith git.

**Comment by mauvilsa** [comment]
@c0ntradicti0n sorry about that! The pagexml library was changed to a submodule some time ago but the readme was not updated to reflect this. I have now added --recursive option to the git clone command so that other people don't encounter the same problem.

**Comment by c0ntradicti0n** [comment]
Ah sorry, that wasn't enogh, just cloned again and the folder is empty.

**Comment by mauvilsa** [comment]
What do you mean the folder is empty? The `git clone --recursive ...` gives you an empty directory?

**Comment by c0ntradicti0n** [comment]
Oh, yeah, I missed that while reading, omg. :)
