### ISSUE TITLE
After compiling

### ISSUE THREAD

**Issue by c0ntradicti0n** [mauvilsa/tesseract-recognize#4]
I get now, when I run it:

./tesseract-recognize -o out.xml --oem 2  page.png 

`terminate called after throwing an instance of 'std::runtime_error'
  what():  PageXML.newXml: either pagens needs to be provided or a schema be loaded
Aborted (core dumped)`

This picture is 
![page](https://user-images.githubusercontent.com/46457469/55904938-437bf380-5bd1-11e9-8a46-c134b2ebb8ee.png)

If you try it to parse this picture, do you get all the rows and columns? I have problems with the layout, that tesseract can detect the most, but for instance 'Hormones' it can't read.

**Comment by mauvilsa** [comment]
@c0ntradicti0n I have now fixed the problem with the namespace. It runs correctly for this image (without the --oem 2 option), but as you have observed not all of the table cells are detected.

**Comment by c0ntradicti0n** [comment]
What a pitty :) Thanks!
