### ISSUE TITLE
docker pull - manifest issues

### ISSUE THREAD

**Issue by rejordan4** [mauvilsa/tesseract-recognize#7]
Hi. Eager to try out your package.  Getting the following errors from docker hub:

**docker pull mauvilsa/tesseract-recognize**
_Using default tag: latest
Error response from daemon: manifest for mauvilsa/tesseract-recognize:latest not found: manifest unknown: manifest unknown_

I can pull "normal" stuff from docker, so I don't think that's the issue.

Thanks

**Comment by mauvilsa** [comment]
There is no `latest` tag for this docker image. You need to give a specific tag. Available ones are in https://hub.docker.com/r/mauvilsa/tesseract-recognize/tags?page=1&ordering=last_updated. The most recent is `docker pull mauvilsa/tesseract-recognize:2021.02.09-ubuntu18.04-pkg`.
